controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - join2
      - joint3
      - joint4
      - joint5
      - big_part_Joint
initial:  # Define initial robot poses.
  - group: arm
    pose: vert